<%@ Page Language="VB" AutoEventWireup="false" ValidateRequest="false" %>
<%@ Import Namespace="CG.New" %>
<%


    Dim myTodos As New Frame(Of Todo)

    myTodos.Query = "SELECT to_dos.* FROM to_dos WHERE project_id = 1 ORDER BY id "
    myTodos.Execute()
    Response.Write(myTodos.Serialize(myTodos))

    Dim myProject As New Frame(Of Project)

    myProject.Query = "SELECT * FROM projects WHERE id > 2"
    Response.Write(myProject.Serialize(myProject))

    'POST back JSON object
    myProject = myProject.Deserialize(Request("object")) 'JSON object generated by Frame(Of Project), loaded in class
    myProject.saveObject(myProject.items) 'Saving changed data in the database


%>